### ISSUE TITLE
Fix Project Escape Site Load Errors

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#2]
- [x] Update Plugins and Monthly Service Fee
- [x] Check Why Project Escape is Having Errors
- [x] Fix Project Escape Site Load Errors
- [x] or Ask If They Want Us to Begin Regression
