### ISSUE TITLE
Migration from GoDaddy Hosting to Piratechs Hosting

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#4]
Finally after years of me trying to convince them to host with us, Brandy and JR agreed as they are fed up with dealing with GoDaddy. They have provided me with the GoDaddy Credentials and we will most likely move them over to Google Domains.

- [ ] Check GoDaddy Status as it Relates to Info@projectescapeatl.com and why they are not receiving emails
- [ ] Save all Important Information and Make a Back Up of their Site
- [ ] Transition to Google Domains
