### ISSUE TITLE
Get Rid of Special Deals Buttons & Duplicate Content on Pages to Speed Up Website

### ISSUE THREAD

**Issue by strawhat19** [Piratechs-LLC/Project-Escape#5]
We need to speed up the website, looking at the code, I've noticed deprecated code blocks which are slowing down the application. The deprecated code blocks are on the pages listed below.

Task: Get rid of Deprecated Code Blocks, Special Deals Buttons & Duplicate Content on the following pages, & Make Sure they are mobile responsive.

- [x] The Will
- [x] Planet Express
- [x] Nautilus
- [x] Vault 202
- [x] Knight's Quest
- [x] Party Room
- [x] Experiences
- [x] Contact
- [x] Make Sure they are Mobile Responsive
     - [x] Experiences Page
          - [x] Rows need to be side by side until screen size = 1350px then it should be collapsed, stacked one on top of the other
          - [x] Once stacked, columns need inner padding or more spacing on mobile only

**Comment by Xuruko** [comment]
Experience Page works for every size except between 1000 px and 768px. Seems like another case of the actual code not updating.

Contact Page works but there's no space between two of the FAQ bars and one of the answers cuts off.

Home Page works except for the "Our Rooms" part that has the blue bars on either side. Starts to overlap at 487px. Might also want to make the News Section "New Room!" and the picture of The Will larger.

**Comment by Xuruko** [comment]
> We need to speed up the website, looking at the code, I've noticed deprecated code blocks which are slowing down the application. The deprecated code blocks are on the pages listed below.
> 
> Task: Get rid of Deprecated Code Blocks, Special Deals Buttons & Duplicate Content on the following pages, & Make Sure they are mobile responsive.
> 
> * [x]  The Will
> * [x]  Planet Express
> * [x]  Nautilus
> * [x]  Vault 202
> * [x]  Knight's Quest
> * [x]  Party Room
> * [ ]  Experiences
> * [x]  Contact
> * [ ]  Home
>   
>   * [ ]  ![image](https://user-images.githubusercontent.com/85896950/182256696-4f207fa7-0497-4020-a926-2db4cb6f27f3.png)
> * [ ]  Make Sure they are Mobile Responsive
>   
>   * [x]  Experiences Page
>     
>     * [x]  Rows need to be side by side until screen size = 1350px then it should be collapsed, stacked one on top of the other
>     * [x]  Once stacked, columns need inner padding or more spacing on mobile only
> * Chandler Paid= 6
> * Unpaid = 4 + 1
